// ARRAY

// DRY - DON'T REPEAT YOURSELF

let student1 = "Mahibullah";
let student2 = "Amanullah";
let student3 = "Suleman";
let student4 = "Fahim";
let student5 = "Hamid";

console.log(student1);

// console.log(studentsName[0]);
// console.log(studentsName[1]);
// console.log(studentsName[2]);
// console.log(studentsName[3]);
// console.log(studentsName[4]);

let studentsName = [
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
  "Mahibullah",
  "Amanullah",
  "Suleman",
  "Fahim",
];

console.log(studentsName.length);

for (let i = 0; i <= studentsName.length - 1; i++) {
  console.log(studentsName[i]);
}

//OBJECT

let laptopData = {
  brand: "HP",
  model: "Pavilion",
  ram: "16GB",
  storage: "512GB SSD",
  processor: "Intel i7",
  price: 1200,
};

let shoaibCar = {
  color: "White",
  carName: "Toyota",
  engineNumber: "LAB56G4",
  numberPlate: "AAQ-673",
};

let zohaibCar = {
  color: "Black",
  carName: "Honda",
  engineNumber: "JSJ8282",
  numberPlate: "BBA-286",
};

let userData = {
  fullName: "",
  firstName: "",
  lastName: "",
  password: "",
  email: "",
  gender: "",
  address: "",
};

let laptop1 = {
  image: "askhdasdhasldjasldhasldhasld",
  description: "aksjdkfhsdjkdqwbklsdfbikbhbrb",
  price: 43434343,
};

let laptop2 = {
  image: "12312312312asldhasldhasld",
  description: "aksqweqweqweqwklsdfbikbhbrb",
  price: 434223243,
};

let laptopDataa = [
  {
    image: "HP KA LAPTOP",
    description: "Acha Laptop",
    price: "232323232",
  },

  {
    image: "Dell ka laptop",
    description: "Average laptop",
    price: "212121",
  },

  {
    image: "Dell ka laptop",
    description: "Average laptop",
    price: "212121",
  },
  {
    image: "Dell ka laptop",
    description: "Average laptop",
    price: "212121",
  },
  {
    image: "Dell ka laptop",
    description: "Average laptop",
    price: "212121",
  },
  {
    image: "Dell ka laptop",
    description: "Average laptop",
    price: "212121",
  },
  {
    image: "Dell ka laptop",
    description: "Average laptop",
    price: "212121",
  },
];

let laptopImages = ["1231231231errt43r34", "12312dasf23e1we12312,"];
